---
title: "Exercise6 - Task4"
output: html_document
---

## Load packages
Check if needed packages are installed and loaded.
```{r, echo=FALSE}
if (!("RPostgreSQL" %in% installed.packages())){
  install.packages("RPostgreSQL")
}
if (!("getPass" %in% installed.packages())){
  install.packages("getPass")
}
require(RPostgreSQL)
require(getPass)
```

## Connect to Server
```{r}
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, host='v45522.1blu.de', port=5432, user=getPass('Provide the user'), 
                 password=getPass('Provide the password'), dbname='datamanagement')

```

```{r}
dbListTables(con)
```

```{sql connection=con}
select * from raw_data where hobo_id=2
```

```{sql connection=con}
create view test as select id, hobo_id from hobos where id=2
```

```{sql connection=con}
select * from test limit 5
```

```{sql connection=con}
select 
hobo_id,
avg(temperature) as mean_day,
variance(temperature) as var_day
from raw_data 
where date_part('hour', tstamp) >= 6 and date_part('hour', tstamp) < 18
group by hobo_id

```

```{sql connection=con}
select 
hobo_id,
avg(temperature) as mean_night,
variance(temperature) as var_night
from raw_data 
where date_part('hour', tstamp) < 6 or date_part('hour', tstamp) >= 18
group by hobo_id

```


```{sql connection=con}
select * from temperatur_indices
```



