---
title: "SQL exercise - Task 4"
description: |
  Load data from PostgreSQL and create impressive plots.
author:
  - name: Mirko Mälicke
    url: https://hyd.iwg.kit.edu/personen_maelicke.php
    affiliation: Karlsruhe Institute for Technology (KIT)
    affiliation_url: https://hyd.iwg.kit.edu
date: "`r Sys.Date()`"
output:  
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  radix::radix_article:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install packages if missing
if (!("RPostgreSQL" %in% installed.packages())){
  install.packages("RPostgreSQL")
}
if (!("getPass" %in% installed.packages())){
  install.packages("getPass")
}

# load packages
require(RPostgreSQL)
require(getPass)

# establish the connection
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, host='v45522.1blu.de', port=5432, user=getPass('Provide the user'), 
                 password=getPass('Provide the password'), dbname='datamanagement')
```

## Solution

*put your results here*


## Hints

The results might be hard to interpret if you just load all data into R. Therefore you can try to load the results from 
the last exercise and compare the calculated indices with each coordinate dimension.
```{sql connection=con, output.var="data"}
select 
  h.hobo_id,
  st_x(h.geom) as x,
  st_y(h.geom) as y,
  avg(rd.temperature) as "mean"
from raw_data rd
join hobos h on h.id=rd.hobo_id
where h.year=2018
group by h.hobo_id, x, y
```

```{r}
require(ggplot2)

ggplot(data, aes(x=x, y=mean)) + 
  geom_point()
```

You can check out more indices, compare to y values and improve the plots.
