---
title: "SQL exercise - Task 4b"
description: |
  Load data from PostgreSQL and create impressive plots.
author:
  - name: Niklas Toensing,
          Lena Schemel,
          Jonas Pyschik
date: "`r Sys.Date()`"
output:  
  html_document:
    number_sections: yes
    toc: yes
    toc_float: yes
  html_notebook:
    number_sections: yes
    toc: yes
    toc_float: yes
  radix::radix_article:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# install packages if missing
if (!("RPostgreSQL" %in% installed.packages())){
  install.packages("RPostgreSQL")
}
if (!("getPass" %in% installed.packages())){
  install.packages("getPass")
}

# load packages
require(RPostgreSQL)
require(getPass)

#--------------------------------------------------
#packages
library(tidyverse)

#neutral ggplot style
neutral <- theme_bw() + theme(panel.grid.major = element_blank(),
                              panel.grid.minor = element_blank(),
                              strip.background = element_rect(colour="grey85"),
                              panel.border = element_rect(colour = "grey85"))


# establish the connection
drv <- dbDriver('PostgreSQL')
con <- dbConnect(drv, host='v45522.1blu.de', port=5432, user=getPass('Provide the user'), 
                 password=getPass('Provide the password'), dbname='datamanagement')
```

## Solution

```{sql connection = con, output.var = "hobo_2020_checked"}

SELECT * FROM quality_checked WHERE tstamp > '2019-12-10' ORDER BY tstamp DESC
 
```




```{r}
avg_hobo_2020 <- hobo_2020_checked %>% 
                  group_by(tstamp) %>% 
                  summarise(mn = mean(value),
                            md = median(value),
                            q5 = quantile(value, 0.05, type = 1),
                            q95 = quantile(value, 0.95, type = 1),
                            mini = min(value),
                            maxi = max(value))%>% 
                  ungroup()
```
  

```{r}
#plot min and max values with mean
ggplot(data = avg_hobo_2020) + neutral + 
  geom_ribbon(aes(x = tstamp, ymin = mini, ymax = maxi), fill = "dodgerblue3", alpha = .3 ) +
  geom_ribbon(aes(x = tstamp, ymin = q5, ymax = q95), fill = "dodgerblue4", alpha = .4 ) +
  geom_line(aes(x = tstamp, y = md), color = "grey30", lwd = 0.8, alpha = 0.5) + 
  geom_line(aes(x = tstamp, y = mn), alpha = 1, lwd = 0.3) +
      #geom_line(data = hobo_2020_checked, aes(x = tstamp, y = value), color = "forestgreen", lwd = 0.1) +
  geom_line(data = filter(hobo_2020_checked, hobo_id == 10350032), aes(x = tstamp, y = value), color = "gold", linetype = "dotted") +
  geom_line(data = filter(hobo_2020_checked, hobo_id == 10347346), aes(x = tstamp, y = value), color = "gold", linetype = "dotted") +
  labs(title = "Mean temperature and Interval of 2020 Hobos", x = "Date", y = "Temperature °C", color = "Legend")

```


```{r}
#plot 5th and 95th percentile with median 
ggplot(data = avg_hobo_2020) + neutral + 
  geom_ribbon(aes(x = tstamp, ymin = q5, ymax = q95), alpha = 0.5, fill = "blue") +
  geom_line(aes(x = tstamp, y = md), col = "black", lwd = 1) + # median
  labs(title = "Median Temperature with 5 & 95 Percentile Interval", x = "Date", y = "Temperature °C")
```



```{r}
disconnect(con)
```